apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
spec:
  selector:
    matchLabels:
      app: music
  replicas: 2
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app.kubernetes.io/name: music
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
