apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx  
spec:
 containers: 
 - name: bear
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
 - name: juice-shop
   image: bkimminich/juice-shop
   ports: 
   - containerPort: 3000